### ISSUE TITLE
Document Vite workaround for import.meta.url

### ISSUE THREAD

**Issue by louispotok** [preflower/react-barcode-scanner#231]
Hi, I just tried to get this working with Vite. It didn't work out-of-the-box, which looks like it's caused by an issue with Vite, but there's a quick workaround. It might save other people some time if this was documented here?

I'm out of my depth on understanding the issue, but it looks like [Vite has problems](https://github.com/vitejs/vite/issues/13530) with `import.meta.url` -- causing errors in development mode and warnings in production mode. The polyfill library that this library relies on seems to trigger those issues. The workaround is to exclude the polyfill library from being optimized by vite in the vite config: 
```
  optimizeDeps: {
    exclude: ['@preflower/barcode-detector-polyfill']
  },
```

**Comment by preflower** [comment]
I have rewritten the project document and added a framework to use guide;
https://reactbarcodescanner.vercel.app/docs/install
