### ISSUE TITLE
Next.js doesn't work

### ISSUE THREAD

**Issue by rafaelpoa** [preflower/react-barcode-scanner#247]
I'm using version 14.0.3, running in development works. But it is not building.

**Failed to compile.**

static/media/index.8f2ed130.mjs from Terser
  x 'import.meta' cannot be used outside of module code.

**I'm importing like this:**
const BarcodeScanner = dynamic(
  () => {
    import("react-barcode-scanner/polyfill"); <--- **Here's the problem**
    return import("react-barcode-scanner").then((mod) => mod.BarcodeScanner);
  },
  { ssr: false }
);

**Comment by preflower** [comment]
Please upgrade to latest or v14.1.0 Next version. and it's worked fine.

**Comment by rafaelpoa** [comment]
Thank you very much for the quick response. I managed to run the build after changing to version 14.1.0.

**Comment by preflower** [comment]
There is no new problem, I will turn off this issue
