### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by saurlax** [preflower/react-barcode-scanner#92]
I tried to scan the barcode in https://preflower.github.io/react-barcode-scanner/, but it didn't recognize anything. The image can be displayed normally but the result is always empty. The barcode is very clear and the direction is correct.

**Platform I have tried**:
- Edge 109.0.1518.55 on Windows 11
- Edge 108.0.1462.76 on MagicOS 7.0 (Android 12), ANN-AN00, Camera resolution: 1080x1920

In console, it returns the following:
```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
falling back to ArrayBuffer instantiation
Uncaught (in promise) No width or height
```

I also tested this package in my own local test project, and the above situation also happens.

**Comment by saurlax** [comment]
Hi, I still encountered a few problems. On page https://preflower.github.io/react-barcode-scanner/guide/demo, I still can't get the content. On my PC (Edge 112.0.1722.64, Windows 10), it throws the following message in console.
```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
```
Should I open some browser features?
On my phone (Edge 110.0.1587.66, Android 12), it throws:
```
wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': An argument must be provided, which must be a Response or Promise<Response> object
falling back to ArrayBuffer instantiation
Uncaught (in promise)  {"name": "NotSupportedError", "message": "Barcode Detection not implemented.", "stack": "Error: Barcode Detection not implemented."}
```

There is also another problem when I updated to 1.0.1. 
I am using this package in Vite, it throws:
```
Internal server error: Failed to resolve entry for package "react-barcode-scanner". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "react-barcode-scanner". The package may have incorrect main/module/exports specified in its package.json.
```
I have tried to change `"module": "esm/index.js"` to `"module": "esm/src/index.js"` in `node_modules/react-barcode-scanner/package.json` and it works. But I don't know if this is Vite's mistake or for some other reason. You can see how I use in my project: https://github.com/saurlax/pillbutler/blob/master/views/src/pages/AddPillByScan.jsx

**Comment by preflower** [comment]
There are three problems:
1. just because Chrome FLoC police, don't care.
2. I'm going to try to use Android simulator to reproduce it (Edge browser worked fine in MacOS and iOS).
3. it's caused that update dumi version, not vite's problems, I've fixed it, u can update to latest.

**Comment by preflower** [comment]
sry for let u waiting for long;
i can't reproduce 2nd problem, i'm using Android device(OnePlus A5000, Android 10, Edge 110.0.1722.46) and emulator(Pixel2, Android 12, Edge latest) test demo, there're working fine;

**Comment by saurlax** [comment]
I tried it again on my phone and it still didn't work. This is probably just a problem with my phone, I'll try it a few more times on other devices

**Comment by preflower** [comment]
This issue has not been updated for a long time, I will turn it off, if still exist please create a new issue or reply to me.
